[package]
name = "imnodes-sys-bindgen"
version = "0.2.2"
authors = ["Benedikt Mandelkow"]
edition = "2021"

[dependencies]
bindgen = "0.66.1"
imgui-sys = {git = "https://github.com/imgui-rs/imgui-rs.git", rev = "67f7f11363e62f09aa0e1288a17800e505860486"}
